# Generated by Django 3.2.21 on 2024-03-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('document', models.CharField(blank=True, max_length=20, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('plan', models.CharField(default='Free', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
